remove(where=this.id==id.open)
remove(find='Добавить новый элемент в сетевое окружение')
remove(find='Печать')
remove(find='Настроить папку')
remove(find='Вырезать')
remove(find='Закрепить в меню "Пуск"')
remove(find='7-Zip' type='drive')
remove(find='Группировка')
remove(find='Открыть в новом окне')
remove(find='Открыть окно PowerShell здесь')
remove(find='Открыть в  командной строке')
remove(find='Запуск от имени администратора')
remove(find='Параметры экрана')
remove(find='Открыть как переносное устройство')
remove(find='Записать образ диска')
remove(find='Run script')
remove(find='Run with UI access')
modify(find='Открыть с помощью' vis=key.shift())
modify(find='Копировать как путь' title='Скопировать путь' vis=key.shift())
modify(find='Hide/Show' title='Скрытые файлы' image=icon.show_hidden_files)
modify(find='7-Zip' image=icon.new_folder)
modify(find='Выполнить с помощью Powershell' title='Выполнить')
modify(find='Сделать фоном рабочего стола' title='Сделать фоном')
modify(find='Открыть расположение папки' title='Расположение папки')
modify(find='Edit Script' title='Изменить' image=icon.edit)